import { Injectable } from '@angular/core';
import { webSocket, WebSocketSubject } from 'rxjs/webSocket';
import { environment } from '../environments/environment';
import { HttpClient } from '@angular/common/http';

interface MessageData {
    message: string;
    time?: string;
}

@Injectable({
    providedIn: 'root',
})
export class WebsocketService {
    private socket$!: WebSocketSubject<any>;
    public receivedData: MessageData[] = [];

    constructor(private http: HttpClient) { }

    public connect(): void {
        if (!this.socket$ || this.socket$.closed) {
            this.socket$ = webSocket(environment.webSocketUrl);

            this.socket$.subscribe((data: MessageData) => {
                this.receivedData.push(data);
            });
        }
    }

    markets(tick_num: number) {
        return this.http.get(environment.marketsUrl + "?tick_num=" + tick_num);
    }

    sendMessage(message: string) {
        this.socket$.next({ message });
    }

    close() {
        this.socket$.complete();
    }

    data = {
        "searchresult": [
            {
                "segment": "NSE",
                "companyShortName": "FACT",
                "bestBuyQty": 360111,
                "nseScripCode": "FACTEQ",
                "fiftyTwoWeekLowPrice": 112.5,
                "absoluteChange": 68.7,
                "companyId": "11995",
                "updatedDateTime": "04:00 PM | 31 Oct 2023",
                "ticker": "FACT",
                "value": "304.58",
                "current": 756.05,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=FACTEQ&exchangense",
                "sectorName": "Fertilisers",
                "marketCap": 48921.88,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "100.0",
                "eventCount": 0,
                "bestBuyPrice": "756.05",
                "bestSellQty": 0,
                "companyName": "The Fertilisers and Chemicals Travancore Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 4108.34,
                "fiftyTwoWeekHighPrice": 774.95,
                "percentChange": 9.99,
                "volume": 4108341,
                "sectorId": 520,
                "companyName2": "The Fertilisers and Chemicals Travancore Ltd.",
                "high": 756.05,
                "low": 686.25,
                "seoName": "the-fertilisers-and-chemicals-travancore-ltd",
                "bestSellPrice": ".00",
                "fiftytwoWeekHighDateTime": "Oct 18 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Nov 01 2022 12:00 AM",
                "highPercentGap": 2.5,
                "lowPercentGap": 85.12,
                "isPsu": true,
                "belowDaysHigh": 0.0,
                "belowDaysHighPerChange": 0.0,
                "aboveDaysLow": 69.8,
                "aboveDaysLowPerChange": 10.17,
                "weekHighPrice": 756.9,
                "monthHighPrice": 774.95,
                "month3HighPrice": 774.95,
                "month6HighPrice": 774.95,
                "yearHighPrice": 774.95,
                "weekLowPrice": 636.35,
                "monthLowPrice": 506.0,
                "month3LowPrice": 413.15,
                "month6LowPrice": 294.0,
                "yearLowPrice": 112.5,
                "barGraphValue1W": "99.29",
                "barGraphValue1M": "92.97",
                "barGraphValue3M": "94.78",
                "barGraphValue6M": "96.07",
                "barGraphValue1Y": "97.15",
                "noOfShares": 647071974,
                "open": 690.35,
                "totalTradedValue": 304.58,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Pidilite Ind",
                "bestBuyQty": 10,
                "nseScripCode": "PIDILITINDEQ",
                "fiftyTwoWeekLowPrice": 2250.05,
                "absoluteChange": 145.85,
                "companyId": "10460",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "PIDILITIND",
                "value": "564.83",
                "current": 2458.0,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=PIDILITINDEQ&exchangense",
                "sectorName": "Diversified",
                "marketCap": 124980.19,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "84.33",
                "eventCount": 0,
                "bestBuyPrice": "2456.00",
                "bestSellQty": 116,
                "companyName": "Pidilite Industries Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 2314.74,
                "fiftyTwoWeekHighPrice": 2796.0,
                "percentChange": 6.3,
                "volume": 2314742,
                "sectorId": 516,
                "companyName2": "Pidilite Industries Ltd.",
                "high": 2478.0,
                "low": 2350.35,
                "seoName": "pidilite-industries-ltd",
                "bestSellPrice": "2457.00",
                "fiftytwoWeekHighDateTime": "Dec 07 2022 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 24 2023 12:00 AM",
                "highPercentGap": 13.75,
                "lowPercentGap": 8.46,
                "isPsu": false,
                "belowDaysHigh": -20.0,
                "belowDaysHighPerChange": -0.81,
                "aboveDaysLow": 107.65,
                "aboveDaysLowPerChange": 4.58,
                "weekHighPrice": 2478.0,
                "monthHighPrice": 2497.5,
                "month3HighPrice": 2643.95,
                "month6HighPrice": 2735.0,
                "yearHighPrice": 2796.0,
                "weekLowPrice": 2292.55,
                "monthLowPrice": 2292.55,
                "month3LowPrice": 2292.55,
                "month6LowPrice": 2292.55,
                "yearLowPrice": 2250.05,
                "barGraphValue1W": "89.22",
                "barGraphValue1M": "80.73",
                "barGraphValue3M": "47.08",
                "barGraphValue6M": "37.39",
                "barGraphValue1Y": "38.09",
                "noOfShares": 508345285,
                "open": 2364.0,
                "totalTradedValue": 564.83,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "P&G",
                "bestBuyQty": 13,
                "nseScripCode": "PGHHEQ",
                "fiftyTwoWeekLowPrice": 13140.1,
                "absoluteChange": 858.91,
                "companyId": "13253",
                "updatedDateTime": "03:40 PM | 31 Oct 2023",
                "ticker": "PGHH",
                "value": "77.19",
                "current": 17540.7,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=PGHHEQ&exchangense",
                "sectorName": "FMCG",
                "marketCap": 56938.4,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "85.74",
                "eventCount": 0,
                "bestBuyPrice": "17398.00",
                "bestSellQty": 37,
                "companyName": "Procter & Gamble Hygiene & Healthcare Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 44.19,
                "fiftyTwoWeekHighPrice": 18597.95,
                "percentChange": 5.14,
                "volume": 44193,
                "sectorId": 522,
                "companyName2": "Procter & Gamble Hygiene & Healthcare Ltd.",
                "high": 17673.0,
                "low": 16745.15,
                "seoName": "procter-gamble-hygiene-healthcare-ltd",
                "bestSellPrice": "17452.90",
                "fiftytwoWeekHighDateTime": "Sep 28 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 29 2023 12:00 AM",
                "highPercentGap": 6.03,
                "lowPercentGap": 25.09,
                "isPsu": false,
                "belowDaysHigh": -132.3,
                "belowDaysHighPerChange": -0.75,
                "aboveDaysLow": 795.55,
                "aboveDaysLowPerChange": 4.75,
                "weekHighPrice": 17673.0,
                "monthHighPrice": 18125.75,
                "month3HighPrice": 18597.95,
                "month6HighPrice": 18597.95,
                "yearHighPrice": 18597.95,
                "weekLowPrice": 16740.0,
                "monthLowPrice": 16625.2,
                "month3LowPrice": 15155.55,
                "month6LowPrice": 13362.0,
                "yearLowPrice": 13140.1,
                "barGraphValue1W": "85.82",
                "barGraphValue1M": "61.01",
                "barGraphValue3M": "69.29",
                "barGraphValue6M": "79.81",
                "barGraphValue1Y": "80.63",
                "noOfShares": 32460736,
                "open": 17290.0,
                "totalTradedValue": 77.19,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Patanjali Foods",
                "bestBuyQty": 54472,
                "nseScripCode": "PATANJALIBE",
                "fiftyTwoWeekLowPrice": 853.5,
                "absoluteChange": 59.16,
                "companyId": "13169",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "PATANJALI",
                "value": "80.75",
                "current": 1367.9,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=PATANJALIBE&exchangense",
                "sectorName": "FMCG",
                "marketCap": 49517.28,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "90.26",
                "eventCount": 0,
                "bestBuyPrice": "1374.15",
                "bestSellQty": 0,
                "companyName": "Patanjali Foods Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 598.99,
                "fiftyTwoWeekHighPrice": 1439.0,
                "percentChange": 4.51,
                "volume": 598989,
                "sectorId": 522,
                "companyName2": "Patanjali Foods Ltd.",
                "high": 1374.15,
                "low": 1310.0,
                "seoName": "patanjali-foods-ltd",
                "bestSellPrice": ".00",
                "fiftytwoWeekHighDateTime": "Oct 31 2022 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 20 2023 12:00 AM",
                "highPercentGap": 5.2,
                "lowPercentGap": 37.61,
                "isPsu": false,
                "belowDaysHigh": -6.25,
                "belowDaysHighPerChange": -0.45,
                "aboveDaysLow": 57.9,
                "aboveDaysLowPerChange": 4.42,
                "weekHighPrice": 1374.15,
                "monthHighPrice": 1374.15,
                "month3HighPrice": 1393.0,
                "month6HighPrice": 1393.0,
                "yearHighPrice": 1439.0,
                "weekLowPrice": 1192.75,
                "monthLowPrice": 1192.75,
                "month3LowPrice": 1192.75,
                "month6LowPrice": 918.0,
                "yearLowPrice": 853.5,
                "barGraphValue1W": "96.55",
                "barGraphValue1M": "96.55",
                "barGraphValue3M": "87.47",
                "barGraphValue6M": "94.72",
                "barGraphValue1Y": "87.86",
                "noOfShares": 361994853,
                "open": 1320.0,
                "totalTradedValue": 80.75,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Macrotech Developers",
                "bestBuyQty": 62,
                "nseScripCode": "LODHAEQ",
                "fiftyTwoWeekLowPrice": 355.5,
                "absoluteChange": 27.56,
                "companyId": "20352",
                "updatedDateTime": "03:54 PM | 31 Oct 2023",
                "ticker": "LODHA",
                "value": "85.78",
                "current": 787.7,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=LODHAEQ&exchangense",
                "sectorName": "Real Estate",
                "marketCap": 75963.43,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "75.86",
                "eventCount": 0,
                "bestBuyPrice": "785.35",
                "bestSellQty": 1,
                "companyName": "Macrotech Developers Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 1090.57,
                "fiftyTwoWeekHighPrice": 829.4,
                "percentChange": 3.62,
                "volume": 1090566,
                "sectorId": 552,
                "companyName2": "Macrotech Developers Ltd.",
                "high": 794.0,
                "low": 767.9,
                "seoName": "macrotech-developers-ltd",
                "bestSellPrice": "787.35",
                "fiftytwoWeekHighDateTime": "Oct 11 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 24 2023 12:00 AM",
                "highPercentGap": 5.29,
                "lowPercentGap": 54.87,
                "isPsu": false,
                "belowDaysHigh": -6.3,
                "belowDaysHighPerChange": -0.79,
                "aboveDaysLow": 19.8,
                "aboveDaysLowPerChange": 2.58,
                "weekHighPrice": 811.0,
                "monthHighPrice": 829.4,
                "month3HighPrice": 829.4,
                "month6HighPrice": 829.4,
                "yearHighPrice": 829.4,
                "weekLowPrice": 701.7,
                "monthLowPrice": 701.7,
                "month3LowPrice": 641.05,
                "month6LowPrice": 445.5,
                "yearLowPrice": 355.5,
                "barGraphValue1W": "78.68",
                "barGraphValue1M": "67.35",
                "barGraphValue3M": "77.86",
                "barGraphValue6M": "89.14",
                "barGraphValue1Y": "91.2",
                "noOfShares": 963955282,
                "open": 768.8,
                "totalTradedValue": 85.78,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Solar Ind.",
                "bestBuyQty": 3,
                "nseScripCode": "SOLARINDSEQ",
                "fiftyTwoWeekLowPrice": 3453.35,
                "absoluteChange": 191.56,
                "companyId": "15283",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "SOLARINDS",
                "value": "33.66",
                "current": 5500.5,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=SOLARINDSEQ&exchangense",
                "sectorName": "Chemicals",
                "marketCap": 49774.05,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "68.14",
                "eventCount": 0,
                "bestBuyPrice": "5480.10",
                "bestSellQty": 3,
                "companyName": "Solar Industries India Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 61.69,
                "fiftyTwoWeekHighPrice": 5590.05,
                "percentChange": 3.6,
                "volume": 61686,
                "sectorId": 512,
                "companyName2": "Solar Industries India Ltd.",
                "high": 5590.05,
                "low": 5309.0,
                "seoName": "solar-industries-india-ltd",
                "bestSellPrice": "5489.95",
                "fiftytwoWeekHighDateTime": "Oct 31 2023 03:59 PM",
                "fiftytwoWeekLowDateTime": "Jul 11 2023 12:00 AM",
                "highPercentGap": 1.63,
                "lowPercentGap": 37.22,
                "isPsu": false,
                "belowDaysHigh": -89.55,
                "belowDaysHighPerChange": -1.6,
                "aboveDaysLow": 191.5,
                "aboveDaysLowPerChange": 3.61,
                "weekHighPrice": 5590.05,
                "monthHighPrice": 5590.05,
                "month3HighPrice": 5590.05,
                "month6HighPrice": 5590.05,
                "yearHighPrice": 5590.05,
                "weekLowPrice": 4995.85,
                "monthLowPrice": 4699.9,
                "month3LowPrice": 3758.05,
                "month6LowPrice": 3453.35,
                "yearLowPrice": 3453.35,
                "barGraphValue1W": "84.93",
                "barGraphValue1M": "89.94",
                "barGraphValue3M": "95.11",
                "barGraphValue6M": "95.81",
                "barGraphValue1Y": "95.81",
                "noOfShares": 90490055,
                "open": 5340.0,
                "totalTradedValue": 33.66,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "REC",
                "bestBuyQty": 1354,
                "nseScripCode": "RECLTDEQ",
                "fiftyTwoWeekLowPrice": 99.0,
                "absoluteChange": 9.21,
                "companyId": "4616",
                "updatedDateTime": "03:58 PM | 31 Oct 2023",
                "ticker": "RECLTD",
                "value": "399.77",
                "current": 287.6,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=RECLTDEQ&exchangense",
                "sectorName": "Term Lending Institutions",
                "marketCap": 75731.52,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "89.08",
                "eventCount": 0,
                "bestBuyPrice": "287.70",
                "bestSellQty": 757,
                "companyName": "REC Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 14086.06,
                "fiftyTwoWeekHighPrice": 299.2,
                "percentChange": 3.3,
                "volume": 14086055,
                "sectorId": 560,
                "companyName2": "REC Ltd.",
                "high": 288.85,
                "low": 277.4,
                "seoName": "rec-ltd",
                "bestSellPrice": "287.95",
                "fiftytwoWeekHighDateTime": "Oct 16 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Nov 10 2022 12:00 AM",
                "highPercentGap": 4.03,
                "lowPercentGap": 65.58,
                "isPsu": true,
                "belowDaysHigh": -1.25,
                "belowDaysHighPerChange": -0.43,
                "aboveDaysLow": 10.2,
                "aboveDaysLowPerChange": 3.68,
                "weekHighPrice": 291.15,
                "monthHighPrice": 299.2,
                "month3HighPrice": 299.2,
                "month6HighPrice": 299.2,
                "yearHighPrice": 299.2,
                "weekLowPrice": 259.45,
                "monthLowPrice": 259.45,
                "month3LowPrice": 191.45,
                "month6LowPrice": 125.15,
                "yearLowPrice": 99.0,
                "barGraphValue1W": "88.8",
                "barGraphValue1M": "70.82",
                "barGraphValue3M": "89.23",
                "barGraphValue6M": "93.34",
                "barGraphValue1Y": "94.21",
                "noOfShares": 2633224000,
                "open": 279.2,
                "totalTradedValue": 399.77,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Power Finance Corp.",
                "bestBuyQty": 143,
                "nseScripCode": "PFCEQ",
                "fiftyTwoWeekLowPrice": 90.4,
                "absoluteChange": 7.66,
                "companyId": "4519",
                "updatedDateTime": "03:57 PM | 31 Oct 2023",
                "ticker": "PFC",
                "value": "274.50",
                "current": 246.6,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=PFCEQ&exchangense",
                "sectorName": "Term Lending Institutions",
                "marketCap": 81380.51,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "86.16",
                "eventCount": 0,
                "bestBuyPrice": "247.60",
                "bestSellQty": 1073,
                "companyName": "Power Finance Corporation Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 11247.49,
                "fiftyTwoWeekHighPrice": 258.2,
                "percentChange": 3.2,
                "volume": 11247490,
                "sectorId": 560,
                "companyName2": "Power Finance Corporation Ltd.",
                "high": 247.7,
                "low": 239.75,
                "seoName": "power-finance-corporation-ltd",
                "bestSellPrice": "247.70",
                "fiftytwoWeekHighDateTime": "Oct 16 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Oct 31 2022 12:00 AM",
                "highPercentGap": 4.7,
                "lowPercentGap": 63.34,
                "isPsu": true,
                "belowDaysHigh": -1.1,
                "belowDaysHighPerChange": -0.44,
                "aboveDaysLow": 6.85,
                "aboveDaysLowPerChange": 2.86,
                "weekHighPrice": 250.95,
                "monthHighPrice": 258.2,
                "month3HighPrice": 258.2,
                "month6HighPrice": 258.2,
                "yearHighPrice": 258.2,
                "weekLowPrice": 225.5,
                "monthLowPrice": 225.5,
                "month3LowPrice": 199.64,
                "month6LowPrice": 126.92,
                "yearLowPrice": 90.4,
                "barGraphValue1W": "82.91",
                "barGraphValue1M": "64.53",
                "barGraphValue3M": "80.19",
                "barGraphValue6M": "91.16",
                "barGraphValue1Y": "93.09",
                "noOfShares": 2640081408,
                "open": 240.9,
                "totalTradedValue": 274.5,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "SBI Life",
                "bestBuyQty": 3,
                "nseScripCode": "SBILIFEEQ",
                "fiftyTwoWeekLowPrice": 1054.0,
                "absoluteChange": 41.65,
                "companyId": "2898",
                "updatedDateTime": "03:53 PM | 31 Oct 2023",
                "ticker": "SBILIFE",
                "value": "311.02",
                "current": 1367.85,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=SBILIFEEQ&exchangense",
                "sectorName": "Financial Services",
                "marketCap": 136934.14,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "86.49",
                "eventCount": 0,
                "bestBuyPrice": "1371.45",
                "bestSellQty": 208,
                "companyName": "SBI Life Insurance Company Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 2287.99,
                "fiftyTwoWeekHighPrice": 1393.0,
                "percentChange": 3.14,
                "volume": 2287988,
                "sectorId": 521,
                "companyName2": "SBI Life Insurance Company Ltd.",
                "high": 1375.4,
                "low": 1319.5,
                "seoName": "sbi-life-insurance-company-ltd",
                "bestSellPrice": "1371.75",
                "fiftytwoWeekHighDateTime": "Sep 18 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 20 2023 12:00 AM",
                "highPercentGap": 1.84,
                "lowPercentGap": 22.94,
                "isPsu": true,
                "belowDaysHigh": -7.55,
                "belowDaysHighPerChange": -0.55,
                "aboveDaysLow": 48.35,
                "aboveDaysLowPerChange": 3.66,
                "weekHighPrice": 1375.4,
                "monthHighPrice": 1375.4,
                "month3HighPrice": 1393.0,
                "month6HighPrice": 1393.0,
                "yearHighPrice": 1393.0,
                "weekLowPrice": 1290.75,
                "monthLowPrice": 1264.35,
                "month3LowPrice": 1251.65,
                "month6LowPrice": 1130.15,
                "yearLowPrice": 1054.0,
                "barGraphValue1W": "91.08",
                "barGraphValue1M": "93.2",
                "barGraphValue3M": "82.21",
                "barGraphValue6M": "90.43",
                "barGraphValue1Y": "92.58",
                "noOfShares": 1000965645,
                "open": 1325.0,
                "totalTradedValue": 311.02,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Dalmia Bharat",
                "bestBuyQty": 250,
                "nseScripCode": "DALBHARATEQ",
                "fiftyTwoWeekLowPrice": 1535.5,
                "absoluteChange": 60.3,
                "companyId": "1846307",
                "updatedDateTime": "03:51 PM | 31 Oct 2023",
                "ticker": "DALBHARAT",
                "value": "100.52",
                "current": 2104.25,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=DALBHARATEQ&exchangense",
                "sectorName": "Cement",
                "marketCap": 39461.08,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "90.71",
                "eventCount": 0,
                "bestBuyPrice": "2096.50",
                "bestSellQty": 9,
                "companyName": "Dalmia Bharat Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 481.22,
                "fiftyTwoWeekHighPrice": 2424.75,
                "percentChange": 2.95,
                "volume": 481220,
                "sectorId": 511,
                "companyName2": "Dalmia Bharat Ltd.",
                "high": 2109.8,
                "low": 2050.05,
                "seoName": "dalmia-bharat-ltd",
                "bestSellPrice": "2097.90",
                "fiftytwoWeekHighDateTime": "Sep 15 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Oct 31 2022 12:00 AM",
                "highPercentGap": 15.23,
                "lowPercentGap": 27.03,
                "isPsu": false,
                "belowDaysHigh": -5.55,
                "belowDaysHighPerChange": -0.26,
                "aboveDaysLow": 54.2,
                "aboveDaysLowPerChange": 2.64,
                "weekHighPrice": 2169.4,
                "monthHighPrice": 2417.95,
                "month3HighPrice": 2424.75,
                "month6HighPrice": 2424.75,
                "yearHighPrice": 2424.75,
                "weekLowPrice": 1995.05,
                "monthLowPrice": 1995.05,
                "month3LowPrice": 1873.3,
                "month6LowPrice": 1873.3,
                "yearLowPrice": 1535.5,
                "barGraphValue1W": "62.63",
                "barGraphValue1M": "25.82",
                "barGraphValue3M": "41.88",
                "barGraphValue6M": "41.88",
                "barGraphValue1Y": "63.96",
                "noOfShares": 187480361,
                "open": 2054.9,
                "totalTradedValue": 100.52,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Colgate-Palmolive",
                "bestBuyQty": 76,
                "nseScripCode": "COLPALEQ",
                "fiftyTwoWeekLowPrice": 1434.6,
                "absoluteChange": 60.0,
                "companyId": "13873",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "COLPAL",
                "value": "134.20",
                "current": 2113.8,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=COLPALEQ&exchangense",
                "sectorName": "FMCG",
                "marketCap": 57492.32,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "82.38",
                "eventCount": 0,
                "bestBuyPrice": "2111.55",
                "bestSellQty": 11,
                "companyName": "Colgate-Palmolive (India) Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 638.95,
                "fiftyTwoWeekHighPrice": 2129.4,
                "percentChange": 2.92,
                "volume": 638945,
                "sectorId": 522,
                "companyName2": "Colgate-Palmolive (India) Ltd.",
                "high": 2127.45,
                "low": 2050.0,
                "seoName": "colgate-palmolive-india-ltd",
                "bestSellPrice": "2112.00",
                "fiftytwoWeekHighDateTime": "Oct 20 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Jan 30 2023 12:00 AM",
                "highPercentGap": 0.74,
                "lowPercentGap": 32.13,
                "isPsu": false,
                "belowDaysHigh": -13.65,
                "belowDaysHighPerChange": -0.64,
                "aboveDaysLow": 63.8,
                "aboveDaysLowPerChange": 3.11,
                "weekHighPrice": 2127.45,
                "monthHighPrice": 2129.4,
                "month3HighPrice": 2129.4,
                "month6HighPrice": 2129.4,
                "yearHighPrice": 2129.4,
                "weekLowPrice": 2005.0,
                "monthLowPrice": 1969.15,
                "month3LowPrice": 1909.0,
                "month6LowPrice": 1560.0,
                "yearLowPrice": 1434.6,
                "barGraphValue1W": "88.85",
                "barGraphValue1M": "90.27",
                "barGraphValue3M": "92.92",
                "barGraphValue6M": "97.26",
                "barGraphValue1Y": "97.75",
                "noOfShares": 271985634,
                "open": 2053.0,
                "totalTradedValue": 134.2,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Tube Investments",
                "bestBuyQty": 10,
                "nseScripCode": "TIINDIAEQ",
                "fiftyTwoWeekLowPrice": 2375.0,
                "absoluteChange": 89.3,
                "companyId": "67230",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "TIINDIA",
                "value": "68.31",
                "current": 3150.2,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=TIINDIAEQ&exchangense",
                "sectorName": "Consumer Durables",
                "marketCap": 60899.29,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "72.27",
                "eventCount": 0,
                "bestBuyPrice": "3157.75",
                "bestSellQty": 199,
                "companyName": "Tube Investments of India Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 216.95,
                "fiftyTwoWeekHighPrice": 3736.4,
                "percentChange": 2.91,
                "volume": 216954,
                "sectorId": 514,
                "companyName2": "Tube Investments of India Ltd.",
                "high": 3179.0,
                "low": 3075.15,
                "seoName": "tube-investments-of-india-ltd",
                "bestSellPrice": "3159.00",
                "fiftytwoWeekHighDateTime": "Sep 11 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 20 2023 12:00 AM",
                "highPercentGap": 18.61,
                "lowPercentGap": 24.61,
                "isPsu": false,
                "belowDaysHigh": -28.8,
                "belowDaysHighPerChange": -0.91,
                "aboveDaysLow": 75.05,
                "aboveDaysLowPerChange": 2.44,
                "weekHighPrice": 3179.0,
                "monthHighPrice": 3179.0,
                "month3HighPrice": 3736.4,
                "month6HighPrice": 3736.4,
                "yearHighPrice": 3736.4,
                "weekLowPrice": 2879.25,
                "monthLowPrice": 2879.25,
                "month3LowPrice": 2758.0,
                "month6LowPrice": 2517.4,
                "yearLowPrice": 2375.0,
                "barGraphValue1W": "90.39",
                "barGraphValue1M": "90.39",
                "barGraphValue3M": "40.09",
                "barGraphValue6M": "51.91",
                "barGraphValue1Y": "56.94",
                "noOfShares": 193260791,
                "open": 3084.5,
                "totalTradedValue": 68.31,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "KPIT Tech",
                "bestBuyQty": 1,
                "nseScripCode": "KPITTECHEQ",
                "fiftyTwoWeekLowPrice": 622.55,
                "absoluteChange": 32.15,
                "companyId": "69000",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "KPITTECH",
                "value": "577.85",
                "current": 1217.55,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=KPITTECHEQ&exchangense",
                "sectorName": "IT Software",
                "marketCap": 33378.38,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "32.08",
                "eventCount": 0,
                "bestBuyPrice": "1223.15",
                "bestSellQty": 83,
                "companyName": "KPIT Technologies Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 4684.04,
                "fiftyTwoWeekHighPrice": 1254.7,
                "percentChange": 2.71,
                "volume": 4684035,
                "sectorId": 566,
                "companyName2": "KPIT Technologies Ltd.",
                "high": 1254.7,
                "low": 1200.0,
                "seoName": "kpit-technologies-ltd",
                "bestSellPrice": "1223.45",
                "fiftytwoWeekHighDateTime": "Oct 31 2023 03:59 PM",
                "fiftytwoWeekLowDateTime": "Dec 23 2022 12:00 AM",
                "highPercentGap": 3.05,
                "lowPercentGap": 48.87,
                "isPsu": false,
                "belowDaysHigh": -37.15,
                "belowDaysHighPerChange": -2.96,
                "aboveDaysLow": 17.55,
                "aboveDaysLowPerChange": 1.46,
                "weekHighPrice": 1254.7,
                "monthHighPrice": 1254.7,
                "month3HighPrice": 1254.7,
                "month6HighPrice": 1254.7,
                "yearHighPrice": 1254.7,
                "weekLowPrice": 1091.2,
                "monthLowPrice": 1091.2,
                "month3LowPrice": 1038.0,
                "month6LowPrice": 874.5,
                "yearLowPrice": 622.55,
                "barGraphValue1W": "77.28",
                "barGraphValue1M": "77.28",
                "barGraphValue3M": "82.86",
                "barGraphValue6M": "90.23",
                "barGraphValue1Y": "94.12",
                "noOfShares": 274143808,
                "open": 1200.0,
                "totalTradedValue": 577.85,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Berger Paints",
                "bestBuyQty": 7,
                "nseScripCode": "BERGEPAINTEQ",
                "fiftyTwoWeekLowPrice": 439.11,
                "absoluteChange": 12.86,
                "companyId": "13971",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "BERGEPAINT",
                "value": "75.51",
                "current": 558.6,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=BERGEPAINTEQ&exchangense",
                "sectorName": "Building Materials",
                "marketCap": 65116.39,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "70.17",
                "eventCount": 0,
                "bestBuyPrice": "558.25",
                "bestSellQty": 44,
                "companyName": "Berger Paints (India) Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 1354.52,
                "fiftyTwoWeekHighPrice": 679.75,
                "percentChange": 2.35,
                "volume": 1354517,
                "sectorId": 509,
                "companyName2": "Berger Paints (India) Ltd.",
                "high": 563.0,
                "low": 548.25,
                "seoName": "berger-paints-india-ltd",
                "bestSellPrice": "558.40",
                "fiftytwoWeekHighDateTime": "Sep 22 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 03 2023 12:00 AM",
                "highPercentGap": 21.69,
                "lowPercentGap": 21.39,
                "isPsu": false,
                "belowDaysHigh": -4.4,
                "belowDaysHighPerChange": -0.78,
                "aboveDaysLow": 10.35,
                "aboveDaysLowPerChange": 1.89,
                "weekHighPrice": 585.05,
                "monthHighPrice": 585.9,
                "month3HighPrice": 679.75,
                "month6HighPrice": 679.75,
                "yearHighPrice": 679.75,
                "weekLowPrice": 533.1,
                "monthLowPrice": 533.1,
                "month3LowPrice": 533.1,
                "month6LowPrice": 496.375,
                "yearLowPrice": 439.2917,
                "barGraphValue1W": "49.09",
                "barGraphValue1M": "48.3",
                "barGraphValue3M": "17.39",
                "barGraphValue6M": "33.93",
                "barGraphValue1Y": "49.62",
                "noOfShares": 971422485,
                "open": 549.3,
                "totalTradedValue": 75.51,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Titan Company ",
                "bestBuyQty": 57,
                "nseScripCode": "TITANEQ",
                "fiftyTwoWeekLowPrice": 2269.6,
                "absoluteChange": 73.21,
                "companyId": "12903",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "TITAN",
                "value": "389.19",
                "current": 3189.65,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=TITANEQ&exchangense",
                "sectorName": "Gems and Jewellery",
                "marketCap": 283172.71,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "86.31",
                "eventCount": 0,
                "bestBuyPrice": "3193.90",
                "bestSellQty": 218,
                "companyName": "Titan Company Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 1235.48,
                "fiftyTwoWeekHighPrice": 3352.0,
                "percentChange": 2.34,
                "volume": 1235478,
                "sectorId": 524,
                "companyName2": "Titan Company Ltd.",
                "high": 3205.8,
                "low": 3087.85,
                "seoName": "titan-company-ltd",
                "bestSellPrice": "3195.00",
                "fiftytwoWeekHighDateTime": "Sep 18 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 02 2023 12:00 AM",
                "highPercentGap": 5.09,
                "lowPercentGap": 28.84,
                "isPsu": false,
                "belowDaysHigh": -16.15,
                "belowDaysHighPerChange": -0.5,
                "aboveDaysLow": 101.8,
                "aboveDaysLowPerChange": 3.3,
                "weekHighPrice": 3274.95,
                "monthHighPrice": 3329.0,
                "month3HighPrice": 3352.0,
                "month6HighPrice": 3352.0,
                "yearHighPrice": 3352.0,
                "weekLowPrice": 3087.25,
                "monthLowPrice": 3075.0,
                "month3LowPrice": 2882.45,
                "month6LowPrice": 2619.5,
                "yearLowPrice": 2269.6,
                "barGraphValue1W": "54.56",
                "barGraphValue1M": "45.14",
                "barGraphValue3M": "65.42",
                "barGraphValue6M": "77.84",
                "barGraphValue1Y": "85.0",
                "noOfShares": 887786160,
                "open": 3119.6,
                "totalTradedValue": 389.19,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Indian Bank",
                "bestBuyQty": 75,
                "nseScripCode": "INDIANBEQ",
                "fiftyTwoWeekLowPrice": 241.0,
                "absoluteChange": 8.45,
                "companyId": "8614",
                "updatedDateTime": "03:55 PM | 31 Oct 2023",
                "ticker": "INDIANB",
                "value": "50.47",
                "current": 420.05,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=INDIANBEQ&exchangense",
                "sectorName": "Banks",
                "marketCap": 52314.76,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "73.8",
                "eventCount": 0,
                "bestBuyPrice": "419.05",
                "bestSellQty": 54,
                "companyName": "Indian Bank",
                "exchangeID": "50",
                "volumeInThousand": 1202.66,
                "fiftyTwoWeekHighPrice": 446.5,
                "percentChange": 2.05,
                "volume": 1202664,
                "sectorId": 15,
                "companyName2": "Indian Bank",
                "high": 422.5,
                "low": 413.15,
                "seoName": "indian-bank",
                "bestSellPrice": "419.55",
                "fiftytwoWeekHighDateTime": "Sep 27 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Nov 02 2022 12:00 AM",
                "highPercentGap": 6.3,
                "lowPercentGap": 42.63,
                "isPsu": true,
                "belowDaysHigh": -2.45,
                "belowDaysHighPerChange": -0.58,
                "aboveDaysLow": 6.9,
                "aboveDaysLowPerChange": 1.67,
                "weekHighPrice": 425.3,
                "monthHighPrice": 445.1,
                "month3HighPrice": 446.5,
                "month6HighPrice": 446.5,
                "yearHighPrice": 446.5,
                "weekLowPrice": 396.4,
                "monthLowPrice": 396.4,
                "month3LowPrice": 335.6,
                "month6LowPrice": 268.0,
                "yearLowPrice": 241.0,
                "barGraphValue1W": "81.83",
                "barGraphValue1M": "48.56",
                "barGraphValue3M": "76.15",
                "barGraphValue6M": "85.18",
                "barGraphValue1Y": "87.13",
                "noOfShares": 1245441139,
                "open": 413.35,
                "totalTradedValue": 50.47,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Bajaj Holdings",
                "bestBuyQty": 3,
                "nseScripCode": "BAJAJHLDNGEQ",
                "fiftyTwoWeekLowPrice": 5560.15,
                "absoluteChange": 132.15,
                "companyId": "13977",
                "updatedDateTime": "03:51 PM | 31 Oct 2023",
                "ticker": "BAJAJHLDNG",
                "value": "13.71",
                "current": 6926.45,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=BAJAJHLDNGEQ&exchangense",
                "sectorName": "Holding Company",
                "marketCap": 77086.89,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "83.75",
                "eventCount": 0,
                "bestBuyPrice": "6906.05",
                "bestSellQty": 20,
                "companyName": "Bajaj Holdings & Investment Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 19.89,
                "fiftyTwoWeekHighPrice": 7640.0,
                "percentChange": 1.94,
                "volume": 19889,
                "sectorId": 526,
                "companyName2": "Bajaj Holdings & Investment Ltd.",
                "high": 6949.9,
                "low": 6805.55,
                "seoName": "bajaj-holdings-investment-ltd",
                "bestSellPrice": "6915.00",
                "fiftytwoWeekHighDateTime": "Jul 26 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Jan 20 2023 12:00 AM",
                "highPercentGap": 10.3,
                "lowPercentGap": 19.73,
                "isPsu": false,
                "belowDaysHigh": -23.45,
                "belowDaysHighPerChange": -0.34,
                "aboveDaysLow": 120.9,
                "aboveDaysLowPerChange": 1.78,
                "weekHighPrice": 7165.0,
                "monthHighPrice": 7165.0,
                "month3HighPrice": 7570.35,
                "month6HighPrice": 7640.0,
                "yearHighPrice": 7640.0,
                "weekLowPrice": 6650.0,
                "monthLowPrice": 6627.9,
                "month3LowPrice": 6627.9,
                "month6LowPrice": 6279.05,
                "yearLowPrice": 5560.15,
                "barGraphValue1W": "53.68",
                "barGraphValue1M": "55.59",
                "barGraphValue3M": "31.68",
                "barGraphValue6M": "47.57",
                "barGraphValue1Y": "65.69",
                "noOfShares": 111293510,
                "open": 6811.55,
                "totalTradedValue": 13.71,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Prestige Estate",
                "bestBuyQty": 15,
                "nseScripCode": "PRESTIGEEQ",
                "fiftyTwoWeekLowPrice": 391.0,
                "absoluteChange": 14.41,
                "companyId": "32683",
                "updatedDateTime": "04:00 PM | 31 Oct 2023",
                "ticker": "PRESTIGE",
                "value": "77.08",
                "current": 765.7,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=PRESTIGEEQ&exchangense",
                "sectorName": "Real Estate",
                "marketCap": 30693.98,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "69.3",
                "eventCount": 0,
                "bestBuyPrice": "762.05",
                "bestSellQty": 6,
                "companyName": "Prestige Estates Projects Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 1020.36,
                "fiftyTwoWeekHighPrice": 819.6,
                "percentChange": 1.91,
                "volume": 1020355,
                "sectorId": 552,
                "companyName2": "Prestige Estates Projects Ltd.",
                "high": 778.5,
                "low": 736.8,
                "seoName": "prestige-estates-projects-ltd",
                "bestSellPrice": "762.50",
                "fiftytwoWeekHighDateTime": "Oct 26 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Feb 27 2023 12:00 AM",
                "highPercentGap": 7.04,
                "lowPercentGap": 48.94,
                "isPsu": false,
                "belowDaysHigh": -12.8,
                "belowDaysHighPerChange": -1.64,
                "aboveDaysLow": 28.9,
                "aboveDaysLowPerChange": 3.92,
                "weekHighPrice": 819.6,
                "monthHighPrice": 819.6,
                "month3HighPrice": 819.6,
                "month6HighPrice": 819.6,
                "yearHighPrice": 819.6,
                "weekLowPrice": 711.0,
                "monthLowPrice": 592.1,
                "month3LowPrice": 543.0,
                "month6LowPrice": 471.3,
                "yearLowPrice": 391.0,
                "barGraphValue1W": "50.37",
                "barGraphValue1M": "76.31",
                "barGraphValue3M": "80.51",
                "barGraphValue6M": "84.52",
                "barGraphValue1Y": "87.42",
                "noOfShares": 400861654,
                "open": 752.45,
                "totalTradedValue": 77.08,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Union Bank India",
                "bestBuyQty": 1175,
                "nseScripCode": "UNIONBANKEQ",
                "fiftyTwoWeekLowPrice": 51.2,
                "absoluteChange": 1.9,
                "companyId": "12261",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "UNIONBANK",
                "value": "272.88",
                "current": 101.6,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=UNIONBANKEQ&exchangense",
                "sectorName": "Banks",
                "marketCap": 75310.47,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "21.57",
                "eventCount": 0,
                "bestBuyPrice": "101.20",
                "bestSellQty": 1178,
                "companyName": "Union Bank of India",
                "exchangeID": "50",
                "volumeInThousand": 26692.15,
                "fiftyTwoWeekHighPrice": 113.35,
                "percentChange": 1.9,
                "volume": 26692147,
                "sectorId": 15,
                "companyName2": "Union Bank of India",
                "high": 103.6,
                "low": 101.05,
                "seoName": "union-bank-of-india",
                "bestSellPrice": "101.25",
                "fiftytwoWeekHighDateTime": "Oct 04 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Nov 03 2022 12:00 AM",
                "highPercentGap": 11.56,
                "lowPercentGap": 49.61,
                "isPsu": true,
                "belowDaysHigh": -2.0,
                "belowDaysHighPerChange": -1.93,
                "aboveDaysLow": 0.55,
                "aboveDaysLowPerChange": 0.54,
                "weekHighPrice": 103.6,
                "monthHighPrice": 113.35,
                "month3HighPrice": 113.35,
                "month6HighPrice": 113.35,
                "yearHighPrice": 113.35,
                "weekLowPrice": 91.25,
                "monthLowPrice": 91.25,
                "month3LowPrice": 84.85,
                "month6LowPrice": 68.0,
                "yearLowPrice": 51.2,
                "barGraphValue1W": "83.81",
                "barGraphValue1M": "46.83",
                "barGraphValue3M": "58.77",
                "barGraphValue6M": "74.09",
                "barGraphValue1Y": "81.09",
                "noOfShares": 7412448217,
                "open": 101.2,
                "totalTradedValue": 272.88,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Oberoi Realty",
                "bestBuyQty": 4,
                "nseScripCode": "OBEROIRLTYEQ",
                "fiftyTwoWeekLowPrice": 790.1,
                "absoluteChange": 20.35,
                "companyId": "32621",
                "updatedDateTime": "03:45 PM | 31 Oct 2023",
                "ticker": "OBEROIRLTY",
                "value": "44.77",
                "current": 1137.85,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=OBEROIRLTYEQ&exchangense",
                "sectorName": "Real Estate",
                "marketCap": 41372.48,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "82.72",
                "eventCount": 0,
                "bestBuyPrice": "1137.80",
                "bestSellQty": 12,
                "companyName": "Oberoi Realty Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 395.16,
                "fiftyTwoWeekHighPrice": 1206.9,
                "percentChange": 1.82,
                "volume": 395162,
                "sectorId": 552,
                "companyName2": "Oberoi Realty Ltd.",
                "high": 1142.1,
                "low": 1117.5,
                "seoName": "oberoi-realty-ltd",
                "bestSellPrice": "1138.00",
                "fiftytwoWeekHighDateTime": "Sep 11 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Jan 27 2023 12:00 AM",
                "highPercentGap": 6.07,
                "lowPercentGap": 30.56,
                "isPsu": false,
                "belowDaysHigh": -4.25,
                "belowDaysHighPerChange": -0.37,
                "aboveDaysLow": 20.35,
                "aboveDaysLowPerChange": 1.82,
                "weekHighPrice": 1142.1,
                "monthHighPrice": 1169.0,
                "month3HighPrice": 1206.9,
                "month6HighPrice": 1206.9,
                "yearHighPrice": 1206.9,
                "weekLowPrice": 1051.1,
                "monthLowPrice": 1051.1,
                "month3LowPrice": 1051.1,
                "month6LowPrice": 884.75,
                "yearLowPrice": 790.1,
                "barGraphValue1W": "95.33",
                "barGraphValue1M": "73.58",
                "barGraphValue3M": "55.68",
                "barGraphValue6M": "78.57",
                "barGraphValue1Y": "83.43",
                "noOfShares": 363602237,
                "open": 1122.0,
                "totalTradedValue": 44.77,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "HDFC Life",
                "bestBuyQty": 371,
                "nseScripCode": "HDFCLIFEEQ",
                "fiftyTwoWeekLowPrice": 457.8,
                "absoluteChange": 10.75,
                "companyId": "3068",
                "updatedDateTime": "03:58 PM | 31 Oct 2023",
                "ticker": "HDFCLIFE",
                "value": "163.87",
                "current": 618.35,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=HDFCLIFEEQ&exchangense",
                "sectorName": "Financial Services",
                "marketCap": 132949.23,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "83.99",
                "eventCount": 0,
                "bestBuyPrice": "620.00",
                "bestSellQty": 212,
                "companyName": "HDFC Life Insurance Company Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 2661.28,
                "fiftyTwoWeekHighPrice": 690.85,
                "percentChange": 1.76,
                "volume": 2661284,
                "sectorId": 521,
                "companyName2": "HDFC Life Insurance Company Ltd.",
                "high": 621.0,
                "low": 604.45,
                "seoName": "hdfc-life-insurance-company-ltd",
                "bestSellPrice": "620.05",
                "fiftytwoWeekHighDateTime": "Jul 13 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 16 2023 12:00 AM",
                "highPercentGap": 11.72,
                "lowPercentGap": 25.96,
                "isPsu": false,
                "belowDaysHigh": -2.65,
                "belowDaysHighPerChange": -0.43,
                "aboveDaysLow": 13.9,
                "aboveDaysLowPerChange": 2.3,
                "weekHighPrice": 644.7,
                "monthHighPrice": 648.45,
                "month3HighPrice": 677.55,
                "month6HighPrice": 690.85,
                "yearHighPrice": 690.85,
                "weekLowPrice": 602.7,
                "monthLowPrice": 600.75,
                "month3LowPrice": 600.75,
                "month6LowPrice": 516.45,
                "yearLowPrice": 457.8,
                "barGraphValue1W": "37.26",
                "barGraphValue1M": "36.9",
                "barGraphValue3M": "22.92",
                "barGraphValue6M": "58.43",
                "barGraphValue1Y": "68.89",
                "noOfShares": 2149679456,
                "open": 607.1,
                "totalTradedValue": 163.87,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Vodafone Idea",
                "bestBuyQty": 5097973,
                "nseScripCode": "IDEAEQ",
                "fiftyTwoWeekLowPrice": 5.7,
                "absoluteChange": 0.2,
                "companyId": "3154",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "IDEA",
                "value": "384.28",
                "current": 11.85,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=IDEAEQ&exchangense",
                "sectorName": "Telecommunications",
                "marketCap": 57685.43,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "36.36",
                "eventCount": 0,
                "bestBuyPrice": "11.85",
                "bestSellQty": 2208681,
                "companyName": "Vodafone Idea Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 321029.39,
                "fiftyTwoWeekHighPrice": 12.5,
                "percentChange": 1.71,
                "volume": 321029390,
                "sectorId": 559,
                "companyName2": "Vodafone Idea Ltd.",
                "high": 12.2,
                "low": 11.65,
                "seoName": "vodafone-idea-ltd",
                "bestSellPrice": "11.90",
                "fiftytwoWeekHighDateTime": "Sep 18 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 31 2023 12:00 AM",
                "highPercentGap": 5.49,
                "lowPercentGap": 51.9,
                "isPsu": false,
                "belowDaysHigh": -0.35,
                "belowDaysHighPerChange": -2.87,
                "aboveDaysLow": 0.2,
                "aboveDaysLowPerChange": 1.72,
                "weekHighPrice": 12.2,
                "monthHighPrice": 12.35,
                "month3HighPrice": 12.5,
                "month6HighPrice": 12.5,
                "yearHighPrice": 12.5,
                "weekLowPrice": 10.5,
                "monthLowPrice": 10.5,
                "month3LowPrice": 7.5,
                "month6LowPrice": 6.55,
                "yearLowPrice": 5.7,
                "barGraphValue1W": "79.41",
                "barGraphValue1M": "72.97",
                "barGraphValue3M": "87.0",
                "barGraphValue6M": "89.08",
                "barGraphValue1Y": "90.44",
                "noOfShares": 48679689205,
                "open": 11.75,
                "totalTradedValue": 384.28,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Trent",
                "bestBuyQty": 3,
                "nseScripCode": "TRENTEQ",
                "fiftyTwoWeekLowPrice": 1155.0,
                "absoluteChange": 34.95,
                "companyId": "13456",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "TRENT",
                "value": "161.04",
                "current": 2154.7,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=TRENTEQ&exchangense",
                "sectorName": "Retail",
                "marketCap": 76596.88,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "77.56",
                "eventCount": 0,
                "bestBuyPrice": "2163.60",
                "bestSellQty": 272,
                "companyName": "Trent Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 749.79,
                "fiftyTwoWeekHighPrice": 2185.0,
                "percentChange": 1.64,
                "volume": 749792,
                "sectorId": 553,
                "companyName2": "Trent Ltd.",
                "high": 2165.0,
                "low": 2119.1,
                "seoName": "trent-ltd",
                "bestSellPrice": "2164.00",
                "fiftytwoWeekHighDateTime": "Sep 26 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Jan 27 2023 12:00 AM",
                "highPercentGap": 1.41,
                "lowPercentGap": 46.4,
                "isPsu": false,
                "belowDaysHigh": -10.3,
                "belowDaysHighPerChange": -0.48,
                "aboveDaysLow": 35.6,
                "aboveDaysLowPerChange": 1.68,
                "weekHighPrice": 2165.0,
                "monthHighPrice": 2165.0,
                "month3HighPrice": 2185.0,
                "month6HighPrice": 2185.0,
                "yearHighPrice": 2185.0,
                "weekLowPrice": 1945.0,
                "monthLowPrice": 1945.0,
                "month3LowPrice": 1670.4,
                "month6LowPrice": 1306.2,
                "yearLowPrice": 1155.0,
                "barGraphValue1W": "95.32",
                "barGraphValue1M": "95.32",
                "barGraphValue3M": "94.11",
                "barGraphValue6M": "96.55",
                "barGraphValue1Y": "97.06",
                "noOfShares": 355487461,
                "open": 2140.9,
                "totalTradedValue": 161.04,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "Indian Oil Corp.",
                "bestBuyQty": 35009,
                "nseScripCode": "IOCEQ",
                "fiftyTwoWeekLowPrice": 68.1,
                "absoluteChange": 1.46,
                "companyId": "11924",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "IOC",
                "value": "258.65",
                "current": 89.7,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=IOCEQ&exchangense",
                "sectorName": "Gas & Petroleum",
                "marketCap": 126667.51,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "87.23",
                "eventCount": 0,
                "bestBuyPrice": "89.85",
                "bestSellQty": 19500,
                "companyName": "Indian Oil Corporation Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 29025.47,
                "fiftyTwoWeekHighPrice": 101.45,
                "percentChange": 1.64,
                "volume": 29025469,
                "sectorId": 523,
                "companyName2": "Indian Oil Corporation Ltd.",
                "high": 90.0,
                "low": 87.65,
                "seoName": "indian-oil-corporation-ltd",
                "bestSellPrice": "89.90",
                "fiftytwoWeekHighDateTime": "Jul 10 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Oct 31 2022 12:00 AM",
                "highPercentGap": 13.1,
                "lowPercentGap": 24.08,
                "isPsu": true,
                "belowDaysHigh": -0.3,
                "belowDaysHighPerChange": -0.33,
                "aboveDaysLow": 2.05,
                "aboveDaysLowPerChange": 2.34,
                "weekHighPrice": 90.3,
                "monthHighPrice": 92.5,
                "month3HighPrice": 96.2,
                "month6HighPrice": 101.45,
                "yearHighPrice": 101.45,
                "weekLowPrice": 85.5,
                "monthLowPrice": 85.5,
                "month3LowPrice": 85.5,
                "month6LowPrice": 80.4,
                "yearLowPrice": 68.1,
                "barGraphValue1W": "87.5",
                "barGraphValue1M": "60.0",
                "barGraphValue3M": "39.25",
                "barGraphValue6M": "44.18",
                "barGraphValue1Y": "64.77",
                "noOfShares": 14121238383,
                "open": 89.0,
                "totalTradedValue": 258.65,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            },
            {
                "segment": "NSE",
                "companyShortName": "DLF",
                "bestBuyQty": 195,
                "nseScripCode": "DLFEQ",
                "fiftyTwoWeekLowPrice": 336.5,
                "absoluteChange": 9.05,
                "companyId": "12393",
                "updatedDateTime": "03:59 PM | 31 Oct 2023",
                "ticker": "DLF",
                "value": "603.67",
                "current": 563.5,
                "sparklineURL": "https://marketcharts.indiatimes.com/sparkline?entity=company&width=110&height=50&chartmode=intraday&symbol=DLFEQ&exchangense",
                "sectorName": "Real Estate",
                "marketCap": 139483.81,
                "companyType": "equity",
                "companyTypeId": "5",
                "bargraphValue": "45.14",
                "eventCount": 0,
                "bestBuyPrice": "563.25",
                "bestSellQty": 670,
                "companyName": "DLF Ltd.",
                "exchangeID": "50",
                "volumeInThousand": 10712.51,
                "fiftyTwoWeekHighPrice": 576.75,
                "percentChange": 1.63,
                "volume": 10712514,
                "sectorId": 552,
                "companyName2": "DLF Ltd.",
                "high": 570.55,
                "low": 557.7,
                "seoName": "dlf-ltd",
                "bestSellPrice": "563.45",
                "fiftytwoWeekHighDateTime": "Oct 13 2023 12:00 AM",
                "fiftytwoWeekLowDateTime": "Mar 14 2023 12:00 AM",
                "highPercentGap": 2.35,
                "lowPercentGap": 40.28,
                "isPsu": false,
                "belowDaysHigh": -7.05,
                "belowDaysHighPerChange": -1.24,
                "aboveDaysLow": 5.8,
                "aboveDaysLowPerChange": 1.04,
                "weekHighPrice": 570.55,
                "monthHighPrice": 576.75,
                "month3HighPrice": 576.75,
                "month6HighPrice": 576.75,
                "yearHighPrice": 576.75,
                "weekLowPrice": 513.5,
                "monthLowPrice": 513.5,
                "month3LowPrice": 463.05,
                "month6LowPrice": 420.05,
                "yearLowPrice": 336.5,
                "barGraphValue1W": "87.64",
                "barGraphValue1M": "79.05",
                "barGraphValue3M": "88.35",
                "barGraphValue6M": "91.54",
                "barGraphValue1Y": "94.48",
                "noOfShares": 2475311706,
                "open": 559.0,
                "totalTradedValue": 603.67,
                "day2PriceDate": 1698345000000,
                "day3PriceDate": 1698258600000,
                "day4PriceDate": 1698172200000,
                "day1PriceDate": 1698604200000,
                "smeFlag": false
            }
        ],
        "pagesummary": {
            "totalRecords": 99,
            "tooltiptext": "Top Gainers (Live) shows the list of stocks that have gained the most in % terms compared to their last closing prices. Click on durations of 1 week, 1 month, 3 months, 6 months or 1year to view the top gainers for the selected period. Click on the stock symbol to view company details. ",
            "totalpages": 4,
            "pagesize": 25,
            "stattype": "Top Gainers",
            "indexvalue": "2694.34",
            "pageno": 1,
            "exchange": "NSE",
            "lasttradeddate": "31-October-2023 16:15:56"
        }
    }
}